# Generated by Django 3.0.7 on 2020-08-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=305)),
                ('url', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0, max_length=4)),
                ('rating', models.FloatField(default=0.0, max_length=4)),
            ],
            options={
                'verbose_name': 'upload_video',
                'verbose_name_plural': 'upload_videos',
                'db_table': 'upload_video',
                'managed': False,
            },
        ),
    ]
